// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: followToUser.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedToUser = `-- name: CreateFeedToUser :one
INSERT INTO feedToUser (id, createdAt, updatedAt, user_id, feed_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, createdat, updatedat, user_id, feed_id
`

type CreateFeedToUserParams struct {
	ID        uuid.UUID
	Createdat time.Time
	Updatedat time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

func (q *Queries) CreateFeedToUser(ctx context.Context, arg CreateFeedToUserParams) (Feedtouser, error) {
	row := q.db.QueryRowContext(ctx, createFeedToUser,
		arg.ID,
		arg.Createdat,
		arg.Updatedat,
		arg.UserID,
		arg.FeedID,
	)
	var i Feedtouser
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.Updatedat,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}
